services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "5000" # Isse app host network ke port 5000 par expose nahi hogi, sirf Docker internal network mein expose hogi.

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80" # Host ka port 80 map kiya container ke port 80 se
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app # Nginx container tabhi chalega jab app container start ho chuka ho
